Repository prgrms-web-devcourse/Team_Alchomist_ShakeNMatch_BE, pull requests merged in 2021-12, with the labels that each got.

#1 [SM-66] fix: 야물 mysql 방언 hbm2ddl: auto: update 설정
  src/main/resources/application.yml
Labels: 🐞 Fix

#3 [SM73] ci/cd: ec2로 자동화 cd 배포
  .github/workflows/ec2.yml
Labels: 🚀 CI/CD

#4 [SM-76] chore: 공통에러코드 추가
  src/main/java/com/shake_match/alchomist/global/ErrorCode.java
  src/main/java/com/shake_match/alchomist/global/NotFoundException.java
Labels: ⚙️ chore

#9 [SM-87] chore: IntelliJ IDEA 관련 설정 추가
  .gitignore
Labels: ⚙️ chore

#10 [SM-77] feat: 관리자 페이지 칵테일 추가 삭제 기능
  src/main/java/com/shake_match/alchomist/cocktail/controller/CocktailController.java
  src/main/java/com/shake_match/alchomist/cocktail/convertor/CocktailConvertor.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/CreateCocktailRequest.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/SearchResponse.java
  src/main/java/com/shake_match/alchomist/cocktail/service/CocktailService.java
  src/main/java/com/shake_match/alchomist/cocktail/service/CocktailServiceImpl.java
Labels: ⭐ Feat

#11 [SM-16] feat: User 기능 개발
  src/main/java/com/shake_match/alchomist/cocktail/domain/Cocktail.java
  src/main/java/com/shake_match/alchomist/global/ErrorCode.java
  src/main/java/com/shake_match/alchomist/users/Users.java
  src/main/java/com/shake_match/alchomist/users/controller/UserController.java
  src/main/java/com/shake_match/alchomist/users/converter/UserConverter.java
  src/main/java/com/shake_match/alchomist/users/dto/request/UserBookmarkRequest.java
  src/main/java/com/shake_match/alchomist/users/dto/request/UserRequest.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserBookmarkResponse.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserIngredientsResponse.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserLikeResponse.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserResponse.java
  src/main/java/com/shake_match/alchomist/users/repository/UserRepository.java
  src/main/java/com/shake_match/alchomist/users/service/UserService.java
Labels: ⭐ Feat

#12 [SM-35] feat: 사용자는 팝업창에서 재료 판매정보창으로 이동할 수 있다.
  src/main/java/com/shake_match/alchomist/cocktail/domain/Cocktail.java
  src/main/java/com/shake_match/alchomist/global/ErrorCode.java
  src/main/java/com/shake_match/alchomist/ingredient/Ingredient.java
  src/main/java/com/shake_match/alchomist/ingredient/controller/IngredientController.java
  src/main/java/com/shake_match/alchomist/ingredient/converter/IngredientConverter.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/request/IngredientDetailRequest.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/request/IngredientUpdateRequest.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientDetailResponse.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientUpdateResponse.java
  src/main/java/com/shake_match/alchomist/ingredient/repository/IngredientRepository.java
  src/main/java/com/shake_match/alchomist/ingredient/service/IngredientService.java
  src/main/java/com/shake_match/alchomist/users/Users.java
  src/main/java/com/shake_match/alchomist/users/repository/UsersRepository.java
  src/test/java/com/shake_match/alchomist/ingredient/service/IngredientServiceTest.java
Labels: ⭐ Feat

#15 [SM-32] feat, refactor: Review 기능 개발
  src/main/java/com/shake_match/alchomist/global/ErrorCode.java
  src/main/java/com/shake_match/alchomist/review/Review.java
  src/main/java/com/shake_match/alchomist/review/controller/ReviewController.java
  src/main/java/com/shake_match/alchomist/review/converter/ReviewConverter.java
  src/main/java/com/shake_match/alchomist/review/dto/request/ReviewDetailRequest.java
  src/main/java/com/shake_match/alchomist/review/dto/request/ReviewUpdateRequest.java
  src/main/java/com/shake_match/alchomist/review/dto/response/ReviewDetailResponse.java
  src/main/java/com/shake_match/alchomist/review/dto/response/ReviewUpdateResponse.java
  src/main/java/com/shake_match/alchomist/review/repository/ReviewRepository.java
  src/main/java/com/shake_match/alchomist/review/service/ReviewService.java
  src/test/java/com/shake_match/alchomist/review/service/ReviewServiceTest.java
Labels: ⭐ Feat

#16 [SM-101] feat: Ingredient의 API(관리자 모드 포함)
  src/main/java/com/shake_match/alchomist/ingredient/Ingredient.java
  src/main/java/com/shake_match/alchomist/ingredient/controller/IngredientController.java
  src/main/java/com/shake_match/alchomist/ingredient/repository/IngredientRepository.java
  src/main/java/com/shake_match/alchomist/ingredient/service/IngredientService.java
  src/test/java/com/shake_match/alchomist/ingredient/service/IngredientServiceTest.java
Labels: ⭐ Feat

#17 [SM-108] feat: 칵테일 관련 api 수정 & 테스트 & 칵테일 정보 저장 api 추가
  src/main/java/com/shake_match/alchomist/cocktail/controller/CocktailController.java
  src/main/java/com/shake_match/alchomist/cocktail/convertor/CocktailConvertor.java
  src/main/java/com/shake_match/alchomist/cocktail/domain/Cocktail.java
  src/main/java/com/shake_match/alchomist/cocktail/domain/Volume.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/CocktailDetailResponse.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/CreateCocktailRequest.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/SearchResponse.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/VolumeDto.java
  src/main/java/com/shake_match/alchomist/cocktail/repository/VolumeRepository.java
  src/main/java/com/shake_match/alchomist/cocktail/service/CocktailService.java
  src/main/java/com/shake_match/alchomist/cocktail/service/CocktailServiceImpl.java
  src/main/java/com/shake_match/alchomist/ingredient/Ingredient.java
  src/main/java/com/shake_match/alchomist/review/converter/ReviewConverter.java
  src/main/java/com/shake_match/alchomist/review/dto/ReviewDto.java
  src/main/java/com/shake_match/alchomist/theme/controller/ThemeController.java
  src/main/java/com/shake_match/alchomist/theme/convertor/ThemeConvertor.java
  src/main/java/com/shake_match/alchomist/theme/domain/Theme.java
  src/main/java/com/shake_match/alchomist/theme/dto/ThemeDto.java
  src/main/java/com/shake_match/alchomist/theme/repository/ThemeRepository.java
  src/main/java/com/shake_match/alchomist/theme/service/ThemeService.java
  src/main/java/com/shake_match/alchomist/theme/service/ThemeServiceImpl.java
Labels: ⭐ Feat

#18 feat: ci/cd 및 user 기능
  pom.xml
  src/main/java/com/shake_match/alchomist/ingredient/converter/IngredientConverter.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientResponse.java
  src/main/java/com/shake_match/alchomist/review/service/ReviewService.java
  src/main/java/com/shake_match/alchomist/users/Users.java
  src/main/java/com/shake_match/alchomist/users/controller/UserController.java
  src/main/java/com/shake_match/alchomist/users/converter/UserConverter.java
  src/main/java/com/shake_match/alchomist/users/dto/request/UserBookmarkRequest.java
  src/main/java/com/shake_match/alchomist/users/dto/request/UserIngredientRequest.java
  src/main/java/com/shake_match/alchomist/users/dto/request/UserRequest.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserBookmarkResponse.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserDetailResponse.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserIngredientsResponse.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserLikeResponse.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserNicknameResponse.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserResponse.java
  src/main/java/com/shake_match/alchomist/users/repository/UserRepository.java
  src/main/java/com/shake_match/alchomist/users/repository/UsersRepository.java
  src/main/java/com/shake_match/alchomist/users/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/shake_match/alchomist/users/service/UserServiceTest.java
Labels: ⭐ Feat, 🚀 CI/CD

#19 fix: theme로 인한 cocktail 추가 오류 수정
  src/main/java/com/shake_match/alchomist/cocktail/convertor/CocktailConvertor.java
  src/main/java/com/shake_match/alchomist/cocktail/domain/Cocktail.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/CreateCocktailRequest.java
  src/main/java/com/shake_match/alchomist/users/converter/UserConverter.java
  src/test/java/com/shake_match/alchomist/ingredient/service/IngredientServiceTest.java
  src/test/java/com/shake_match/alchomist/review/service/ReviewServiceTest.java
Labels: 🐞 Fix

#21 [SM-156] feat: CORS 전부 풀기
  src/main/java/com/shake_match/alchomist/global/WebMvcConfig.java
Labels: ⭐ Feat, ⚙️ chore

#23 Fix : 칵테일의 변수명 수정 & 필요없는 주석 제거
  src/main/java/com/shake_match/alchomist/cocktail/dto/CocktailDetailResponse.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/CreateCocktailRequest.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/SearchResponse.java
  src/main/java/com/shake_match/alchomist/cocktail/service/CocktailServiceImpl.java
Labels: 🐞 Fix

#25 [SM-100] feat: user의 술장고 기능 구현
  src/main/java/com/shake_match/alchomist/cocktail/dto/CocktailDetailResponse.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/CreateCocktailRequest.java
  src/main/java/com/shake_match/alchomist/cocktail/service/CocktailServiceImpl.java
  src/main/java/com/shake_match/alchomist/global/ErrorCode.java
  src/main/java/com/shake_match/alchomist/ingredient/Ingredient.java
  src/main/java/com/shake_match/alchomist/ingredient/converter/IngredientConverter.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientListResponse.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientToListResponse.java
  src/main/java/com/shake_match/alchomist/ingredient/repository/IngredientRepository.java
  src/main/java/com/shake_match/alchomist/users/Users.java
  src/main/java/com/shake_match/alchomist/users/UsersIngredient.java
  src/main/java/com/shake_match/alchomist/users/controller/UserController.java
  src/main/java/com/shake_match/alchomist/users/converter/UserConverter.java
  src/main/java/com/shake_match/alchomist/users/dto/request/UserIngredientRequest.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserIngredientsResponse.java
  src/main/java/com/shake_match/alchomist/users/repository/UserIngredientRepository.java
  src/main/java/com/shake_match/alchomist/users/service/UserService.java
Labels: ⭐ Feat, ♻️ Refactor

#27 [SM-162] feat: oauth2 카카오 로그인 기능 추가
  keystore.p12
  pom.xml
  src/main/java/com/shake_match/alchomist/configures/JwtConfigure.java
  src/main/java/com/shake_match/alchomist/configures/WebSecurityConfigure.java
  src/main/java/com/shake_match/alchomist/group/domain/Group.java
  src/main/java/com/shake_match/alchomist/group/domain/GroupPermission.java
  src/main/java/com/shake_match/alchomist/group/domain/Permission.java
  src/main/java/com/shake_match/alchomist/group/repository/GroupRepository.java
  src/main/java/com/shake_match/alchomist/jwt/Jwt.java
  src/main/java/com/shake_match/alchomist/jwt/JwtAuthentication.java
  src/main/java/com/shake_match/alchomist/jwt/JwtAuthenticationFilter.java
  src/main/java/com/shake_match/alchomist/jwt/JwtAuthenticationToken.java
  src/main/java/com/shake_match/alchomist/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/shake_match/alchomist/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/shake_match/alchomist/review/controller/ReviewController.java
  src/main/java/com/shake_match/alchomist/review/converter/ReviewConverter.java
  src/main/java/com/shake_match/alchomist/users/Users.java
  src/main/java/com/shake_match/alchomist/users/controller/UserController.java
  src/main/java/com/shake_match/alchomist/users/converter/UserConverter.java
  src/main/java/com/shake_match/alchomist/users/dto/request/UserRequest.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserDetailResponse.java
  src/main/java/com/shake_match/alchomist/users/repository/UserRepository.java
  src/main/java/com/shake_match/alchomist/users/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/sql/data_new.sql
  src/main/resources/sql/schema_new.sql
  src/test/java/com/shake_match/alchomist/ingredient/service/IngredientServiceTest.java
  src/test/java/com/shake_match/alchomist/review/service/ReviewServiceTest.java
  src/test/java/com/shake_match/alchomist/users/service/UserServiceTest.java
Labels: ⭐ Feat

#28 fix: yml 오류 수정
  src/main/resources/application-prod.yml
Labels: 🐞 Fix

#29 ci/cd: https 인증서 도입
  src/main/resources/application-prod.yml
  src/main/resources/keystore.p12
Labels: 🚀 CI/CD

#24 [SM-104] chore: Review의 API
  pom.xml
  src/main/java/com/shake_match/alchomist/AlchomistApplication.java
  src/main/java/com/shake_match/alchomist/amazon/config/MvcConfiguration.java
  src/main/java/com/shake_match/alchomist/amazon/service/S3Service.java
  src/main/java/com/shake_match/alchomist/cocktail/domain/Cocktail.java
  src/main/java/com/shake_match/alchomist/ingredient/Ingredient.java
  src/main/java/com/shake_match/alchomist/ingredient/controller/IngredientController.java
  src/main/java/com/shake_match/alchomist/ingredient/converter/IngredientConverter.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/request/IngredientDetailRequest.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/request/IngredientUpdateRequest.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientDetailResponse.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientUpdateResponse.java
  src/main/java/com/shake_match/alchomist/review/Review.java
  src/main/java/com/shake_match/alchomist/review/controller/ReviewController.java
  src/main/java/com/shake_match/alchomist/review/converter/ReviewConverter.java
  src/main/java/com/shake_match/alchomist/review/dto/ReviewDto.java
  src/main/java/com/shake_match/alchomist/review/dto/request/ReviewDetailRequest.java
  src/main/java/com/shake_match/alchomist/review/dto/request/ReviewUpdateRequest.java
  src/main/java/com/shake_match/alchomist/review/dto/response/ReviewDetailResponse.java
  src/main/java/com/shake_match/alchomist/review/repository/ReviewRepository.java
  src/main/java/com/shake_match/alchomist/review/service/ReviewService.java
  src/main/java/com/shake_match/alchomist/users/Users.java
  src/main/java/com/shake_match/alchomist/users/controller/UserController.java
  src/main/java/com/shake_match/alchomist/users/repository/UserRepository.java
  src/main/java/com/shake_match/alchomist/users/repository/UsersRepository.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/shake_match/alchomist/ingredient/service/IngredientServiceTest.java
  src/test/java/com/shake_match/alchomist/review/service/ReviewServiceTest.java
Labels: ⚙️ chore

#30 [SM-143] feat: S3 이미지 조회/업로드
  src/main/java/com/shake_match/alchomist/cocktail/controller/CocktailController.java
  src/main/java/com/shake_match/alchomist/cocktail/convertor/CocktailConvertor.java
  src/main/java/com/shake_match/alchomist/cocktail/service/CocktailServiceImpl.java
Labels: ⭐ Feat

#31 feat: web configure 무시 패턴 추가
  src/main/java/com/shake_match/alchomist/configures/WebSecurityConfigure.java
  src/main/resources/application-prod.yml
Labels: ⭐ Feat

#32 Feat: 칵테일 정보 response의 재료 type 필드 추가
  src/main/java/com/shake_match/alchomist/cocktail/convertor/CocktailConvertor.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/VolumeDto.java
Labels: ⭐ Feat

#34 chore: Cocktail의 youtubeLink 제거
  src/main/java/com/shake_match/alchomist/cocktail/controller/CocktailController.java
  src/main/java/com/shake_match/alchomist/cocktail/convertor/CocktailConvertor.java
  src/main/java/com/shake_match/alchomist/cocktail/domain/Cocktail.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/CocktailDetailResponse.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/CreateCocktailRequest.java
  src/main/java/com/shake_match/alchomist/ingredient/repository/IngredientRepository.java
  src/test/java/com/shake_match/alchomist/ingredient/service/IngredientServiceTest.java
  src/test/java/com/shake_match/alchomist/review/service/ReviewServiceTest.java
Labels: ⚙️ chore

#33 feat: 재료ID기반 칵테일 배열 반환
  src/main/java/com/shake_match/alchomist/cocktail/domain/CocktailIngredient.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/CocktailSimpleListResponse.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/CocktailSimpleResponse.java
  src/main/java/com/shake_match/alchomist/cocktail/repository/CocktailRepository.java
  src/main/java/com/shake_match/alchomist/ingredient/Ingredient.java
  src/main/java/com/shake_match/alchomist/ingredient/converter/IngredientConverter.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/request/IngredientUpdateRequest.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientDetailResponse.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientListResponse.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientUpdateResponse.java
  src/main/java/com/shake_match/alchomist/users/controller/UserController.java
  src/main/java/com/shake_match/alchomist/users/converter/UserConverter.java
  src/main/java/com/shake_match/alchomist/users/repository/UserRepository.java
  src/main/java/com/shake_match/alchomist/users/service/UserService.java
  src/test/java/com/shake_match/alchomist/ingredient/service/IngredientServiceTest.java
Labels: ⭐ Feat

#35 feat: hbm2ddl DB update로 변경 및 칵테일id1:재료id1매핑 api 추가
  src/main/java/com/shake_match/alchomist/cocktail/controller/CocktailController.java
  src/main/java/com/shake_match/alchomist/cocktail/domain/Cocktail.java
  src/main/java/com/shake_match/alchomist/cocktail/domain/CocktailIngredient.java
  src/main/java/com/shake_match/alchomist/cocktail/repository/CocktailIngredientRepository.java
  src/main/java/com/shake_match/alchomist/cocktail/service/CocktailService.java
  src/main/java/com/shake_match/alchomist/cocktail/service/CocktailServiceImpl.java
  src/main/resources/application-prod.yml
Labels: ⭐ Feat, 🐞 Fix, ♻️ Refactor

#37 feat: 서버인증서 초록도메인 https
  src/main/resources/application-prod.yml
Labels: ♻️ Refactor, ⚙️ chore, 🚀 CI/CD

#36 Feat: 칵테일 API 일부 변경 & oauth 기능을 위한 수정
  src/main/java/com/shake_match/alchomist/cocktail/controller/CocktailController.java
  src/main/java/com/shake_match/alchomist/cocktail/convertor/CocktailConvertor.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/CreateCocktailRequest.java
  src/main/java/com/shake_match/alchomist/cocktail/dto/VolumeDto.java
  src/main/java/com/shake_match/alchomist/cocktail/service/CocktailService.java
  src/main/java/com/shake_match/alchomist/cocktail/service/CocktailServiceImpl.java
  src/main/java/com/shake_match/alchomist/group/domain/Group.java
  src/main/java/com/shake_match/alchomist/group/domain/GroupPermission.java
  src/main/java/com/shake_match/alchomist/group/domain/Permission.java
  src/main/resources/application-prod.yml
  src/main/resources/sql/data_new.sql
  src/main/resources/sql/schema_new.sql
Labels: ⭐ Feat

#38 feat: oauth 가입으로 위한 추가 api
  src/main/java/com/shake_match/alchomist/users/controller/UserController.java
  src/main/java/com/shake_match/alchomist/users/dto/request/UserJoinRequest.java
  src/main/java/com/shake_match/alchomist/users/service/UserService.java
  src/main/resources/sql/schema_new.sql
Labels: ⭐ Feat

#39 fix: api 오류 수정 및 불형 오류 수정
  src/main/java/com/shake_match/alchomist/users/Users.java
  src/main/java/com/shake_match/alchomist/users/converter/UserConverter.java
  src/main/java/com/shake_match/alchomist/users/dto/request/UserJoinRequest.java
  src/main/java/com/shake_match/alchomist/users/dto/request/UserRequest.java
  src/main/java/com/shake_match/alchomist/users/dto/request/UserUpdateRequest.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserDetailResponse.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserUpdateResponse.java
  src/main/java/com/shake_match/alchomist/users/repository/UserRepository.java
  src/main/java/com/shake_match/alchomist/users/service/UserService.java
Labels: 🐞 Fix

#40 chore: 재료의 전체 조회 개수 확장 및 수정(150개)
  src/main/java/com/shake_match/alchomist/cocktail/dto/VolumeDto.java
  src/main/java/com/shake_match/alchomist/global/ErrorCode.java
  src/main/java/com/shake_match/alchomist/ingredient/Ingredient.java
  src/main/java/com/shake_match/alchomist/ingredient/controller/IngredientController.java
  src/main/java/com/shake_match/alchomist/ingredient/converter/IngredientConverter.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/request/IngredientDetailRequest.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/request/IngredientUpdateRequest.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientDetailResponse.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientListResponse.java
  src/main/java/com/shake_match/alchomist/ingredient/dto/response/IngredientUpdateResponse.java
  src/main/java/com/shake_match/alchomist/ingredient/service/IngredientService.java
  src/test/java/com/shake_match/alchomist/ingredient/service/IngredientServiceTest.java
Labels: ⚙️ chore

#41 feat: 유저의 술장고 재료추가시 삭제후 새로 추가
  src/main/java/com/shake_match/alchomist/users/UsersIngredient.java
  src/main/java/com/shake_match/alchomist/users/controller/UserController.java
  src/main/java/com/shake_match/alchomist/users/repository/UserIngredientRepository.java
  src/main/java/com/shake_match/alchomist/users/service/UserService.java
Labels: ⭐ Feat, 🐞 Fix

#44 feat: let's encrypt 재발급(초록자물쇠)
  src/main/resources/application-prod.yml
  src/main/resources/keystore.p12
Labels: ⭐ Feat, 🐞 Fix

#49 chore: review의 dto, converter에 필드 추가 및 review 전체 조회 최대 수 증가
  src/main/java/com/shake_match/alchomist/global/ErrorCode.java
  src/main/java/com/shake_match/alchomist/review/Review.java
  src/main/java/com/shake_match/alchomist/review/controller/ReviewController.java
  src/main/java/com/shake_match/alchomist/review/converter/ReviewConverter.java
  src/main/java/com/shake_match/alchomist/review/dto/request/ReviewDetailRequest.java
  src/main/java/com/shake_match/alchomist/review/dto/response/ReviewDetailResponse.java
  src/main/java/com/shake_match/alchomist/review/repository/ReviewRepository.java
  src/main/java/com/shake_match/alchomist/review/service/ReviewService.java
Labels: ⚙️ chore

#50 fix: UserDetailResponse 반환 시 북마크도 반환추가
  src/main/java/com/shake_match/alchomist/users/converter/UserConverter.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserDetailResponse.java
  src/main/java/com/shake_match/alchomist/users/service/UserService.java
Labels: ⭐ Feat

#51 fix: UserDetailResponse 반환 시 bookmark로 변경
  src/main/java/com/shake_match/alchomist/users/converter/UserConverter.java
  src/main/java/com/shake_match/alchomist/users/dto/response/UserDetailResponse.java
  src/main/java/com/shake_match/alchomist/users/service/UserService.java
Labels: ⭐ Feat
